### ISSUE TITLE
Total hours not shown

### ISSUE THREAD

**Issue by RfpRZ9WPsB** [philippK-de/Collabtive#108]
Hello,

In the timetracker, total hours are not shown.

**Comment by debiruman665** [comment]
Did you finish those tasks?. ie: tick them?

or is the page showing ok but no total hours?

**Comment by RfpRZ9WPsB** [comment]
![timetracker fezis](https://cloud.githubusercontent.com/assets/3878027/16411441/bbd55268-3d2f-11e6-9b84-7de87a3c4783.png)

Also Online feature does not work. Project selector is not visible on the right.

**Comment by philippK-de** [comment]
This seems to be using the current master revision.
You should not do that for real work. It can be broken or missing feature at any time.

The "total hours" is currently not showing because the GUI of Collabtive is undergoing a major revision.
It will be re-enabled before Collabtive 3.0 releases.
I highly recommend you to use the latest stable release for any real work.
https://github.com/philippK-de/Collabtive/releases/tag/2.1.1
